---
abstract: 'A command line tool for launching POE::Component::IRC clients'
author:
  - 'Hinrik Örn Sigurðsson <hinrik.sig@gmail.com>'
build_requires:
  Test::More: 0.47
  Test::Script: 1.07
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Pocoirc
no_index:
  directory:
    - t
    - xt
    - utils
    - example
requires:
  Class::Load: 0.20
  Data::Dump: 0
  IO::WrapOutput: 0.02
  IRC::Utils: 0.07
  JSON::XS: 0
  Module::Pluggable: 0
  POE: 1.310
  POE::Component::Client::DNS: 0.99
  POE::Component::IRC::State: 6.61
  Proc::Daemon: 0.02
  Term::ANSIColor: 0
  Term::Cap: 1.10
  Term::ReadKey: 2.21
  YAML::XS: 0
  perl: 5.008
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=App-Pocoirc
  homepage: http://metacpan.org/release/App-Pocoirc
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hinrik/app-pocoirc.git
version: 0.47
x_authority: cpan:HINRIK
