---
abstract: 'The guts of L<pocoirc>'
author:
  - 'Hinrik Örn Sigurðsson <hinrik.sig@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101612, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Pocoirc
no_index:
  directory:
    - t
    - xt
    - utils
    - example
requires:
  JSON::XS: 0
  POE::Component::IRC::State: 6.34
  POE::Component::Pluggable: 1.26
  Proc::Daemon: 0.02
  Test::More: 0.47
  Test::Script: 1.05
  YAML::XS: 0
  perl: 5.008
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=App-Pocoirc
  homepage: http://search.cpan.org/dist/App-Pocoirc/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hinrik/app-pocoirc.git
version: 0.04
x_authority: cpan:HINRIK
